### ISSUE TITLE
targetUsernames is deprecated, use targetRecipients instead

### ISSUE THREAD

**Issue by reid** [discourse/discourse-bcc#1]
Just tried using discourse-bcc on latest Discourse test-passed, but it appears [targetUsernames is deprecated](https://github.com/discourse/discourse/commit/20d8b49adddd9927af8cdf01104663d412bf33fc#diff-ec84048fe7c87ba06f7a1810149e6beeR79) and the checkbox never appears. The `bccAvailable` function never runs after the PM box opens because this property is never updated.

This is my first contribution to anything in the Discourse community. I'm going to try to raise a PR to fix it, but I may not be doing everything correctly — the maintainers here might get to fixing it faster than I can.

Thank you!

**Comment by eviltrout** [comment]
Thanks. In the future we'd prefer issues like this be brought up on meta.discourse.org.

However this was a great report and I did fix it:

https://github.com/discourse/discourse-bcc/commit/2528a262d49ce537fc068d77ab5427aca4e9ddc9
